services:
  nats-server:
    image: nats:latest
    container_name: nats-jetstream-single-server
    command: ["-js", "-sd", "/data", "--http_port", "8222"]
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - nats:/data
    networks: [nats-dlq]

  nats-dashboard:
    image: mdawar/nats-dashboard
    container_name: nats-dashboard
    ports:
      - 8090:80
    volumes:
      - dashboard:/data
    networks: [nats-dlq]
    depends_on:
      - nats-server

networks:
  nats-dlq:

volumes:
  nats:
  dashboard: